name: Always fail
description: A composite action that always fails.
runs:
  using: composite
  steps:
    - name: Fail
      shell: bash
      run: /bin/false
    - name: Doesn't run
      shell: bash
      run: echo "Doesn't run"
    - name: Always runs
      if: ${{ always() }}
      shell: bash
      run: echo "Always runs"
